# Generated by Django 5.2.1 on 2025-05-28 11:57

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název nemůže být prázdný'}, help_text='Zadejte název programu', max_length=100, verbose_name='Název')),
                ('kategorie', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Hry', 'Hry'), ('Grafika', 'Grafika'), ('Mobilní aplikace', 'Mobilní aplikace'), ('Webové aplikace', 'Webové aplikace'), ('Databáze', 'Databáze'), ('E-commerce', 'E-commerce'), ('Cloudové služby', 'Cloudové služby'), ('CRM', 'CRM'), ('ERP', 'ERP'), ('Bezpečnost', 'Bezpečnost'), ('Programování a vývoj', 'Programování a vývoj'), ('AI', 'AI'), ('Analytika', 'Analytika'), ('Automatizace', 'Automatizace'), ('Testování a QA', 'Testování a QA')], max_length=161, null=True, verbose_name='Kategorie')),
                ('vydani', models.DateField(blank=True, null=True, verbose_name='Datum vydání')),
                ('licence', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Open Source', 'Open Source'), ('Komerční', 'Komerční'), ('Freeware', 'Freeware'), ('Shareware', 'Shareware'), ('Proprietární', 'Proprietární'), ('Public Domain', 'Public Domain'), ('Creative Commons', 'Creative Commons'), ('GPL', 'GPL'), ('MIT', 'MIT'), ('Apache', 'Apache'), ('BSD', 'BSD'), ('LGPL', 'LGPL'), ('EULA', 'EULA'), ('Trial', 'Trial'), ('Předplatné', 'Předplatné')], max_length=129, null=True, verbose_name='Licence')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena (Kč)')),
                ('jazyk', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Angličtina', 'Angličtina'), ('Čeština', 'Čeština'), ('Španělština', 'Španělština'), ('Němčina', 'Němčina'), ('Francouzština', 'Francouzština'), ('Italština', 'Italština'), ('Portugalština', 'Portugalština'), ('Ruština', 'Ruština'), ('Čínština', 'Čínština'), ('Japonština', 'Japonština'), ('Korejština', 'Korejština'), ('Arabština', 'Arabština'), ('Hindština', 'Hindština'), ('Bengálština', 'Bengálština'), ('Nizozemština', 'Nizozemština'), ('Polština', 'Polština'), ('Maďarština', 'Maďarština'), ('Řečtina', 'Řečtina'), ('Turečtina', 'Turečtina'), ('Dánština', 'Dánština')], max_length=207, null=True, verbose_name='Jazyk')),
                ('platforma', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('MacOS', 'MacOS'), ('Android', 'Android'), ('iOS', 'iOS')], max_length=31, null=True, verbose_name='Platforma')),
                ('popis', models.TextField(blank=True, help_text='Stručně popište program', null=True, verbose_name='Popis')),
                ('ikona', models.ImageField(blank=True, null=True, upload_to='ikony', verbose_name='Ikona')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programy',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Vyvojar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Pole nemůže být prázdné'}, help_text='Zadejte jméno nebo přezdívku vývojáře', max_length=50, verbose_name='Jméno')),
                ('email', models.EmailField(help_text='Zadejte e-mailovou adresu vývojáře', max_length=254, verbose_name='E-mail')),
                ('web', models.URLField(blank=True, help_text='Zadejte URL adresu webové stránky vývojáře', null=True, verbose_name='Web')),
                ('informace', models.TextField(blank=True, help_text='Zadejte informace o vývojáři', null=True, verbose_name='Informace')),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profily', verbose_name='Profilový obrázek')),
            ],
            options={
                'verbose_name': 'Vývojář',
                'verbose_name_plural': 'Vývojáři',
                'ordering': ['jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Verze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verze', models.CharField(error_messages={'blank': 'Pole nemůže být prázdné'}, help_text='Zadejte verzi programu', max_length=30, verbose_name='Verze')),
                ('vydani', models.DateField(blank=True, null=True, verbose_name='Datum vydání')),
                ('typ', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Alfa', 'Alfa'), ('Beta', 'Beta'), ('Kandidát na vydání', 'Kandidát na vydání'), ('Stabilní', 'Stabilní'), ('Zastaralé', 'Zastaralé')], max_length=47, null=True, verbose_name='Typ verze')),
                ('popis', models.TextField(blank=True, help_text='Zadejte popis verze', null=True, verbose_name='Popis')),
                ('velikost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Velikost (MB)')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Verze',
                'verbose_name_plural': 'Verze',
                'ordering': ['software', 'verze'],
            },
        ),
        migrations.AddField(
            model_name='software',
            name='vyvojar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.vyvojar', verbose_name='Vývojář'),
        ),
    ]
