# Generated by Django 5.2.1 on 2025-06-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jazyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název jazyka nemůže být prázdný'}, help_text='Zadejte název jazyka', max_length=100, verbose_name='Název jazyka')),
                ('zkratka', models.CharField(help_text='Zadejte zkratku jazyka', max_length=3, verbose_name='Zkratka jazyka')),
                ('vlajka', models.ImageField(upload_to='vlajky', verbose_name='Vlajka jazyka')),
            ],
            options={
                'verbose_name': 'Jazyk',
                'verbose_name_plural': 'Jazyky',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název kategorie nemůže být prázdný'}, help_text='Zadejte název kategorie', max_length=100, verbose_name='Název kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název licence nemůže být prázdný'}, help_text='Zadejte název licence', max_length=100, verbose_name='Název licence')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licence',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Platforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název platformy nemůže být prázdný'}, help_text='Zadejte název platformy', max_length=100, verbose_name='Název platformy')),
            ],
            options={
                'verbose_name': 'Platforma',
                'verbose_name_plural': 'Platformy',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Typ verze nemůže být prázdný'}, help_text='Zadejte typ verze', max_length=50, verbose_name='Typ verze')),
            ],
            options={
                'verbose_name': 'Typ verze',
                'verbose_name_plural': 'Typy verzí',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název nemůže být prázdný'}, help_text='Zadejte název programu', max_length=100, verbose_name='Název')),
                ('vydani', models.DateField(blank=True, null=True, verbose_name='Datum vydání')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena (Kč)')),
                ('popis', models.TextField(blank=True, help_text='Stručně popište program', null=True, verbose_name='Popis')),
                ('ikona', models.ImageField(blank=True, null=True, upload_to='ikony', verbose_name='Ikona')),
                ('url', models.URLField(blank=True, help_text='Zadejte URL adresu programu', null=True, verbose_name='URL')),
                ('jazyk', models.ManyToManyField(help_text='Zadejte jazyk programu', to='web.jazyk', verbose_name='Jazyk')),
                ('kategorie', models.ManyToManyField(help_text='Zadejte název kategorie', to='web.kategorie', verbose_name='Kategorie')),
                ('licence', models.ManyToManyField(help_text='Zadejte název licence', to='web.licence', verbose_name='Licence')),
                ('platforma', models.ManyToManyField(help_text='Zadejte název platformy', to='web.platforma', verbose_name='Platforma')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programy',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='SystemovePozadavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, help_text='Procesor', max_length=100, null=True, verbose_name='Procesor')),
                ('gpu', models.CharField(blank=True, help_text='Grafická karta', max_length=100, null=True, verbose_name='Grafická karta')),
                ('vram', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Video paměť (GB)')),
                ('ram', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='RAM (GB)')),
                ('disk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Disk (GB)')),
                ('os', models.CharField(blank=True, help_text='Operační systém', max_length=100, null=True, verbose_name='Operační systém')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.software', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Systémové požadavky',
                'verbose_name_plural': 'Systémové požadavky',
                'ordering': ['cpu'],
            },
        ),
        migrations.CreateModel(
            name='Verze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verze', models.CharField(error_messages={'blank': 'Pole nemůže být prázdné'}, help_text='Zadejte verzi programu', max_length=30, verbose_name='Verze')),
                ('vydani', models.DateField(blank=True, null=True, verbose_name='Datum vydání')),
                ('popis', models.TextField(blank=True, help_text='Zadejte popis verze', null=True, verbose_name='Popis')),
                ('velikost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Velikost (MB)')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.software', verbose_name='Software')),
                ('typ', models.ManyToManyField(help_text='Zadejte typ verze', to='web.typ', verbose_name='Typ verze')),
            ],
            options={
                'verbose_name': 'Verze',
                'verbose_name_plural': 'Verze',
                'ordering': ['software', 'verze'],
            },
        ),
        migrations.CreateModel(
            name='Vyvojar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Pole nemůže být prázdné'}, help_text='Zadejte jméno nebo přezdívku vývojáře', max_length=50, verbose_name='Jméno')),
                ('email', models.EmailField(help_text='Zadejte e-mailovou adresu vývojáře', max_length=254, verbose_name='E-mail')),
                ('web', models.URLField(blank=True, help_text='Zadejte URL adresu webové stránky vývojáře', null=True, verbose_name='Web')),
                ('informace', models.TextField(blank=True, help_text='Zadejte informace o vývojáři', null=True, verbose_name='Informace')),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profily', verbose_name='Profilový obrázek')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Vývojář',
                'verbose_name_plural': 'Vývojáři',
                'ordering': ['jmeno'],
            },
        ),
    ]
