# Generated by Django 5.2.1 on 2025-06-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vyvojar',
        ),
    ]
